require'gitsigns'.setup()
require'nvim-tree'.setup()
require'nvim-treesitter'.setup()
require'telescope'.setup()

require'alimfeld.options'.setup()
require'alimfeld.mappings'.setup()
require'alimfeld.lsp'.setup()
require'alimfeld.completion'.setup()
require'alimfeld.theme'.setup()
