return {
  { "tpope/vim-sleuth",
    event = "VeryLazy",
  },
  { "tpope/vim-surround",
    event = "VeryLazy",
  },
  { "christoomey/vim-tmux-navigator",
    event = "VeryLazy",
  },
  { "lukas-reineke/indent-blankline.nvim",
    event = "VeryLazy",
    config = true,
  },
  { "folke/which-key.nvim",
    event = "VeryLazy",
    config = true,
  },
  { "numToStr/Comment.nvim",
    event = "VeryLazy",
    config = true,
  },
  { "lewis6991/gitsigns.nvim",
    event = "VeryLazy",
    config = true,
  },
}
