---
- name: Install neovim
  package:
      name: neovim
      state: present
  become: yes

- name: Install plugins
  git:
      repo: https://github.com/{{ item }}
      dest: ~/.local/share/nvim/site/pack/plugins/start/{{ item | basename }}
  loop:
      - mfussenegger/nvim-dap
      - mfussenegger/nvim-jdtls
      - neovim/nvim-lspconfig
      - nvim-lua/plenary.nvim
      - nvim-lua/popup.nvim
      - nvim-telescope/telescope.nvim
      - tpope/vim-surround

- name: Symlink config
  file:
      src: ~/dotfiles/nvim
      dest: ~/.config/nvim
      state: link
